// TODO: ACTION FOR DEMO, Tobe removed soon
export const DEMO_REQUESTING = "DEMO_REQUESTING";
export const DEMO_FULFILLED = "DEMO_FULFILLED";
export const DEMO_REJECTED = "DEMO_REJECTED";
export const SELECT_LOCALE = "SELECT_LOCALE";
